- id: biome-check
  name: biome check
  entry: biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
  language: rust
  types: [text]
  files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro)$"
